[project]
name = "zoom-transcriptions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "driedwater", email = "88548136+driedwater@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.63.0",
    "python-dotenv>=1.2.3",
    "requests>=2.32.4",
    "tqdm>=4.70.1",
    "webvtt-py>=0.5.1",
]

[project.scripts]
zoom-transcriptions = "zoom_transcriptions:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]
